name: Issues

on:
  issues:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
    - name: Check for label
      if: contains(github.event.issue.labels.*.name, 'bug')
      run: |
        echo "This is a bug. Proceeding with triage."
    - name: Assign to team member
      run: |
        echo "Assigning issue to team member for further review."
    - name: Add comment
      run: |
        echo "Thank you for reporting this issue. We will review and respond as soon as possible."
